#!/usr/bin/env python
# license removed for brevity
import rospy
import time
import serial
import socket

def inicio():
    rospy.init_node('escritura_arduino', anonymous = True)

    TCP_IP = '169.254.162.245'
    TCP_PORT = 5001
    BUFFER_SIZE = 30  # Normally 1024, but we want fast response

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((TCP_IP, TCP_PORT))

    ser1 = serial.Serial('/dev/ttyUSB0',4800)
    ser2 = serial.Serial('/dev/ttyUSB1',4800)
    ser3 = serial.Serial('/dev/ttyUSB2',4800)
    ser4 = serial.Serial('/dev/ttyUSB3',4800)

    w1 = "0"
    w2 = "0"
    w3 = "0"
    w4 = "0"
    w5 = "0"

    while not rospy.is_shutdown():


	ser1.write(w1+"\n")
        ser2.write(w2+"\n")
        ser3.write(w3+"\n")
        ser4.write(w4+"\n")


	data = s.recv(BUFFER_SIZE)
	rospy.loginfo(len(data))
	w1, w2, w3, w4, w5 = data.split(",")
	time.sleep(0.012)

if __name__ == '__main__':
    try:
        inicio()
    except rospy.ROSInterruptException:
        pass
